### ISSUE TITLE
The training environment

### ISSUE THREAD

**Issue by ToTensor** [SamsungLabs/imvoxelnet#66]
Could you please run a training sunrgbd data set, I want to configure my environment according to your log, because I have tried many times, in the past two years, some package updates, I can not succeed in training model. If it is convenient for you, could you please send a copy of your latest training log to my email? My email is liuyuan980528@163.com

**Comment by filaPro** [comment]
I also didn't try training from that time. We provide the logs for all models (links are in readme), is something wrong with them? Also training logs from last year can be found [here](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x/configs/imvoxelnet).

**Comment by ToTensor** [comment]
I configured the same environment as the log you gave me last year to train the sunrgbd data set, but it seems that the required parameters in the mmdet3d module are different from the parameters given.
My environment：
`Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /home/ly/cuda-11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.0
OpenCV: 4.7.0
MMCV: 1.6.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.24.1
MMSegmentation: 0.24.1
MMDetection3D: 1.0.0rc4+
spconv2.0: False`
------------------------------------------------------------------------
The problem of reporting errors：
`2023-03-22 18:26:45,454 - mmdet3d - INFO - Set random seed to 0, deterministic: False
/home/ly/Desktop/mmdetection3d/mmdet3d/models/builder.py:86: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
Traceback (most recent call last):
  File "/home/ly/anaconda3/envs/3d3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'voxel_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 139, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/ly/Desktop/mmdetection3d/mmdet3d/models/builder.py", line 93, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/ly/anaconda3/envs/3d3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ly/anaconda3/envs/3d3/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ly/anaconda3/envs/3d3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ImVoxelNet: __init__() got an unexpected keyword argument 'voxel_size'`

**Comment by ToTensor** [comment]
I configured the same environment as the log you gave me last year to train the sunrgbd data set, but it seems that the required parameters in the mmdet3d module are different from the parameters given.
My environment：
`Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /home/ly/cuda-11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.0
OpenCV: 4.7.0
MMCV: 1.6.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.24.1
MMSegmentation: 0.24.1
MMDetection3D: 1.0.0rc4+
spconv2.0: False`
------------------------------------------------------------------------
The problem of reporting errors：
`2023-03-22 18:26:45,454 - mmdet3d - INFO - Set random seed to 0, deterministic: False
/home/ly/Desktop/mmdetection3d/mmdet3d/models/builder.py:86: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
Traceback (most recent call last):
  File "/home/ly/anaconda3/envs/3d3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'voxel_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 139, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/ly/Desktop/mmdetection3d/mmdet3d/models/builder.py", line 93, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/ly/anaconda3/envs/3d3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ly/anaconda3/envs/3d3/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ly/anaconda3/envs/3d3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ImVoxelNet: __init__() got an unexpected keyword argument 'voxel_size'``

**Comment by ToTensor** [comment]
When building the model, there is a voxel_size= (.08,.08.08) in bbox_head type, but there is no such parameter in mmdet3d type. Is it my problem in compiling mmdet3d? But at the end of the compilation, it indicates that the compilation was successful. Besides, I tried to replace the version of mmdet3d, but it still could not be solved. May I ask if you have a better way to solve it?

**Comment by ToTensor** [comment]
It's settled, thank you

**Comment by filaPro** [comment]
Don't quite understand the question. Batch size is equal to `samples_per_gpu` parameter in configs. Nubmer of gpus can be figured out from log files.

**Comment by ToTensor** [comment]
`+-------------+---------+---------+---------+---------+
| classes     | AP_0.25 | AR_0.25 | AP_0.50 | AR_0.50 |
+-------------+---------+---------+---------+---------+
| bed         | 0.0732  | 0.3120  | 0.0033  | 0.0543  |
| sofa        | 0.0044  | 0.1116  | 0.0000  | 0.0048  |
| night_stand | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| dresser     | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| table       | 0.0223  | 0.1414  | 0.0001  | 0.0077  |
| desk        | 0.0028  | 0.0351  | 0.0000  | 0.0005  |
| chair       | 0.0106  | 0.0731  | 0.0003  | 0.0112  |
| toilet      | 0.0011  | 0.0138  | 0.0003  | 0.0069  |
| bathtub     | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| bookshelf   | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
+-------------+---------+---------+---------+---------+
| Overall     | 0.0114  | 0.0687  | 0.0004  | 0.0085  |
+-------------+---------+---------+---------+---------+
2023-03-26 09:57:07,275 - mmdet - INFO - Epoch(val) [12][5285]	bed_AP_0.25: 0.0732, sofa_AP_0.25: 0.0044, night_stand_AP_0.25: 0.0000, dresser_AP_0.25: 0.0000, table_AP_0.25: 0.0223, desk_AP_0.25: 0.0028, chair_AP_0.25: 0.0106, toilet_AP_0.25: 0.0011, bathtub_AP_0.25: 0.0000, bookshelf_AP_0.25: 0.0000, mAP_0.25: 0.0114, bed_rec_0.25: 0.3120, sofa_rec_0.25: 0.1116, night_stand_rec_0.25: 0.0000, dresser_rec_0.25: 0.0000, table_rec_0.25: 0.1414, desk_rec_0.25: 0.0351, chair_rec_0.25: 0.0731, toilet_rec_0.25: 0.0138, bathtub_rec_0.25: 0.0000, bookshelf_rec_0.25: 0.0000, mAR_0.25: 0.0687, bed_AP_0.50: 0.0033, sofa_AP_0.50: 0.0000, night_stand_AP_0.50: 0.0000, dresser_AP_0.50: 0.0000, table_AP_0.50: 0.0001, desk_AP_0.50: 0.0000, chair_AP_0.50: 0.0003, toilet_AP_0.50: 0.0003, bathtub_AP_0.50: 0.0000, bookshelf_AP_0.50: 0.0000, mAP_0.50: 0.0004, bed_rec_0.50: 0.0543, sofa_rec_0.50: 0.0048, night_stand_rec_0.50: 0.0000, dresser_rec_0.50: 0.0000, table_rec_0.50: 0.0077, desk_rec_0.50: 0.0005, chair_rec_0.50: 0.0112, toilet_rec_0.50: 0.0069, bathtub_rec_0.50: 0.0000, bookshelf_rec_0.50: 0.0000, mAR_0.50: 0.0085`
sunrgbd data set trained by myself, very strange effect is not good, training parameters: epochs=12,samples_per_gpu=2, workers_per_gpu=2,
------------------- And when I used your model weight visualization, the image did not frame the object

**Comment by ToTensor** [comment]
Verify with the model you gave, and the results are all 0`+-------------+---------+---------+---------+---------+
| classes     | AP_0.25 | AR_0.25 | AP_0.50 | AR_0.50 |
+-------------+---------+---------+---------+---------+
| bed         | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| night_stand | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| dresser     | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| sofa        | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| chair       | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| table       | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| desk        | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| bookshelf   | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| toilet      | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
| bathtub     | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
+-------------+---------+---------+---------+---------+
| Overall     | 0.0000  | 0.0000  | 0.0000  | 0.0000  |
`

**Comment by filaPro** [comment]
I will check our pre-trained model.

**Comment by ToTensor** [comment]
Looking forward to your reply

**Comment by filaPro** [comment]
Everything is fine on my side. Please make sure you are running corresponding config and checkpoint files like in the example below. Also you may download `sunrgbd_imvoxelnet_*.pkl` from [here](https://github.com/filaPro/tmp/releases/tag/v0.1) to be sure your data pre-processing is ok. Also will now fix minor bugs in `Dockerfile`.
```
python tools/test.py configs/imvoxelnet/imvoxelnet_sunrgbd_fast.py /opt/project/work_dirs/tmp/20211007_105255.pth --eval mAP
```

```
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 5050/5050, 3.1 task/s
+-------------+---------+---------+---------+---------+
| classes     | AP_0.25 | AR_0.25 | AP_0.50 | AR_0.50 |
+-------------+---------+---------+---------+---------+
| bed         | 0.7173  | 0.8874  | 0.3711  | 0.4660  |
| table       | 0.3911  | 0.8301  | 0.0814  | 0.2355  |
| sofa        | 0.5151  | 0.8852  | 0.1372  | 0.3126  |
| chair       | 0.5365  | 0.8057  | 0.1634  | 0.3164  |
| toilet      | 0.7675  | 0.9172  | 0.3644  | 0.4828  |
| desk        | 0.2185  | 0.7800  | 0.0169  | 0.1567  |
| dresser     | 0.2122  | 0.7982  | 0.0248  | 0.1697  |
| night_stand | 0.3460  | 0.8392  | 0.0769  | 0.2784  |
| bookshelf   | 0.0573  | 0.4574  | 0.0009  | 0.0213  |
| bathtub     | 0.3071  | 0.8163  | 0.0560  | 0.1633  |
+-------------+---------+---------+---------+---------+
| Overall     | 0.4069  | 0.8017  | 0.1293  | 0.2603  |
+-------------+---------+---------+---------+---------+

```

**Comment by ToTensor** [comment]
Is there a visualization tool or file that can draw 2d to 3d projection matrix? I'd like to see the characteristics change during retraining

**Comment by filaPro** [comment]
Visualization command can be found in our readme. It calls [this](https://github.com/SamsungLabs/imvoxelnet/blob/master/mmdet3d/datasets/dataset_wrappers.py#L82) function for 2d to 3d projection.

**Comment by ToTensor** [comment]
Hello, I have a question and need your guidance. Is 3D voxel obtained by aggregation of multiple 2D feature maps? That's the sentence I feel I don't understand very well. If you get rgb images as a multi-view with a special case of monocular, is there only one 2d feature to get 3D voxel? Do I understand correctly?

**Comment by filaPro** [comment]
Sure, in monocular case every voxel in 3d corresponds to not more then one pixel in 2d.

**Comment by ToTensor** [comment]
Thank you very much for your diligent reply. May I ask whether only picture information, calibration information and annotation information (image, calib/annos) in pkl files are used in the training or testing of single or multi-view?

**Comment by ToTensor** [comment]
Thank you very much for your bother reply. I am a little unsure about whether only picture information, calibration information and annotation information (image, calib/annos) from pkl files are used in the training or testing of monocular or multi-view, because you said in your paper that "in the proposed method, the final prediction is obtained from 3D feature map. This is similar to the point cloud-based detection problem. On this basis, the neck and head of an off-the-shelf point cloud-based object detector are used without any modifications."

**Comment by filaPro** [comment]
> only picture information, calibration information and annotation information (image, calib/annos) from pkl files are used

Yes, that is true. We just project 2d features to 3d after 2d backbone and say that after that any point cloud ideas can be used (without point cloud or depth information).

**Comment by ToTensor** [comment]
Thank you for your reply. May I ask how to calculate FPS of detection pictures
In tools, I only see the time to compute epoch, but not the time required to test a single image.

**Comment by filaPro** [comment]
As I remember testing script logs smth like `[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 5050/5050, 3.1 task/s` this number roughly represents FPS.

**Comment by ToTensor** [comment]
Thank you for all your help. May I ask whether I can use this trained model to detect pictures in real scenes (outside the training data set)? For example, it can be applied to the actual detection environment. If so, which file to run

**Comment by filaPro** [comment]
I didn't try to run on images outside of our 4 datasets, but it is possible following #55. To start you can probably refactor [pcd_demo.py](https://github.com/SamsungLabs/imvoxelnet/blob/master/demo/pcd_demo.py) to input image instead of point cloud.
