### ISSUE TITLE
Train & eval inputs for different benchmarks

### ISSUE THREAD

**Issue by DianCh** [SamsungLabs/imvoxelnet#67]
Hi! Thank you for releasing this wonderful work! I am wondering how the inputs look like for different benchmarks, like how many images are used to predict the bounding boxes during training and evaluation? Is it stereo pair for KITTI and multi-view for SUN RGB-D/ScanNet (if so, how are the multi-view inputs selected)?

**Comment by filaPro** [comment]
Hi @DianCh ,
We use a single image for KITTI and SUN RGB-D, 6 images for NuScenes and 50 images for ScanNet.

**Comment by DianCh** [comment]
Thank you @filaPro for the reply! Just trying to understand the dataset protocol:

For SUN RGB-D, is it that only visible 3D gt boxes are used for supervision?
For ScanNet, is it that 20/50 images are randomly sampled per scene, and all 3D gt boxes in that scene are used for supervision/evaluation?

**Comment by filaPro** [comment]
For SUN RGB-D all boxes are visible, a a scene is represented by a single rgb-d image. For ScanNet you are right, all boxes are used for supervision and evaluation.
