### ISSUE TITLE
How to calculate the total number of model parameters and floating point calculation？

### ISSUE THREAD

**Issue by ToTensor** [SamsungLabs/imvoxelnet#69]
How to calculate the total number of model parameters and floating point calculation？

**Comment by filaPro** [comment]
```
sum(p.numel() for p in model.parameters() if p.requires_grad)
```
Something like this should work near this [line](https://github.com/SamsungLabs/imvoxelnet/blob/master/tools/train.py#L138)? I'm not sure about a good method for calculating flops(
