### ISSUE TITLE
How to project 2d feature to 3d volume?

### ISSUE THREAD

**Issue by VLadImirluren** [SamsungLabs/imvoxelnet#74]
I am a rookie of 3d perception. Recently I start to be a reseacher in this field.

Can you tell me how you project the 2d feature to 3d volume? I can't understand, it is a ill-posed problem, isn't it?

<img width="545" alt="image" src="https://github.com/SamsungLabs/imvoxelnet/assets/94054234/fa08be15-d16c-4d43-b91b-9202b498193c">

**Comment by VLadImirluren** [comment]
> 

yeah, that's what I wondering about... So what's the corelation between the 3D voxel volume with 2d feature?

I mean several 3d points correspond to one 3d pixel so how did you project 2d feature to 3d volume?

According to the corresponding code, I think you extract the 3d point cloud then put them in 2d voxel volume, right?(I guess)

<img width="1077" alt="image" src="https://github.com/SamsungLabs/imvoxelnet/assets/94054234/12954e3a-c0f4-40c5-8e95-9c7291c723e6">

Thanks to your reply~

Best wishes~

**Comment by filaPro** [comment]
Sure, more formulas about this `backproject` function are given in section 3.1 of our paper.

**Comment by VLadImirluren** [comment]
> Sure, more formulas about this `backproject` function are given in section 3.1 of our paper.

Thanks ！Get it ~
